// Icon shim: the app standardizes on Tabler Icons (https://tabler.io/icons) to match the Tabler
// admin look. Components import icons from here under their familiar names; this module maps each
// to its Tabler equivalent so call sites (`<Plus size={14} />`) stay unchanged. Tabler icons accept
// `size`, `stroke` and `color` props, so they are drop-in replacements.
export {
  IconActivity as Activity,
  IconAlertTriangle as AlertTriangle,
  IconArrowsExchange as ArrowRightLeft,
  IconBook as BookOpen,
  IconRobot as Bot,
  IconBuilding as Building2,
  IconCalendarTime as CalendarClock,
  IconCheck as Check,
  IconCircleCheck as CheckCircle2,
  IconChevronDown as ChevronDown,
  IconChevronUp as ChevronUp,
  IconDatabase as Database,
  IconEdit as Edit,
  IconKey as KeyRound,
  IconLayoutGrid as LayoutGrid,
  IconMapPin as MapPin,
  IconSpeakerphone as Megaphone,
  IconMessageCircle as MessageCircle,
  IconPackage as Package,
  IconPackageImport as PackagePlus,
  IconPlus as Plus,
  IconPower as Power,
  IconCircleOff as PowerOff,
  IconSearch as Search,
  IconSend as Send,
  IconSettings as Settings,
  IconShieldCheck as ShieldCheck,
  IconSparkles as Sparkles,
  IconBuildingStore as Store,
  IconTrash as Trash2,
  IconUserCheck as UserCheck,
  IconUserPlus as UserPlus,
  IconUsers as Users,
  IconWifi as Wifi,
  IconX as X,
} from "@tabler/icons-react";
