// Icon shim: the app standardizes on Lucide (https://lucide.dev) per constitution v2.0.0. Components
// import icons from here under their familiar names; this module maps each to its Lucide equivalent
// so call sites (`<Plus size={14} />`) stay unchanged. Lucide icons accept `size`, `strokeWidth`,
// and `color` props, so they are drop-in replacements.
export {
  Activity,
  AlertTriangle,
  ArrowRightLeft,
  BookOpen,
  Bot,
  Building2,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Database,
  Pencil as Edit,
  KeyRound,
  LayoutGrid,
  MapPin,
  Megaphone,
  MessageCircle,
  Menu,
  Moon,
  Package,
  PackagePlus,
  Plus,
  Power,
  PowerOff,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Sun,
  Trash2,
  UserCheck,
  UserPlus,
  Users,
  Wifi,
  X,
} from "lucide-react";
